### DISCUSSION TITLE
RFC: tile pipelines as "virtual tile sources"

### DISCUSSION THREAD

**Discussion by MichaelKreil** [versatiles-org/versatiles-documentation#26] [Ideas]
## Introduction

VersaTiles should support "virtual tile sources" defined via YAML, allowing users to create flexible and powerful tile processing pipelines. In addition to standard container formats such as `*.versatiles`, `*.mbtiles`, `*.pmtiles`, ... virtual tile sources `*.yaml` will allow for dynamic tile processing and transformation workflows. These pipelines can be used as virtual tile sources for tile conversion, but can also be used as a source for serving map tiles.

## Use cases

- Tile conversion
	- Render vector tiles as image tiles
	- Tracing image tiles to vector tiles
	- Converting between tile formats
- Editing image tiles
	- Recolour tiles
	- Changing resolution
- Editing vector tiles
	- Delete layers
	- Adding layers from other sources
	- Update/remove properties of features
- Merge multiple tile sources
	- Combine zoom levels from different sources, e.g. use zoom levels 1-12 from one source and zoom levels 13-14 from another.
	- Overlay image tiles, e.g. overlay aerial imagery over satellite tiles to create a composite view.

## Example 1: Appending new properties to POI features

This example shows how to open a vector tile containing Points of Interest (POIs) and append new properties to each POI feature by matching the 'id' field from a CSV file.

```YAML
- run: read
  args:
    filename: pois.versatiles

- run: vectortiles_update_properties
  args:
    data_source_path: pois.csv
    id_field_tiles: id
    id_field_values: id
```

## Example 2: Adding a GeoJSON as a layer to vector tiles

This example shows how to read vector tiles from `europe.versatiles` and add a new layer called "overlay" containing geometries from `overlay.geojson`.

```YAML
- run: vectortiles_merge_layer
  sources:
    - run: read
      args:
        filename: europe.versatiles
    
    - run: read_geojson
      args:
        layer_name: overlay
        max_zoom: 8
        filename: overlay.geojson
```

### Supported operations

1. **Reader**: Read tiles from a tile container or create tiles from a geometry or image file.
2. **Transformer**: transforms tiles.
3. **Composer**: Merge/join/overlay multiple tile sources into a single tile source.
### Pipeline Definition

A pipeline is defined as a sequence of operations, where each operation specifies:
- The operation to be performed (`run`).
- The arguments required by the operation (`args`).
- The sources to be used (`source`) - only for Composers.

## Documentation

If you run `versatiles help pipeline` you get a documentation of all operation, e.g.:

<img width="1040" alt="image" src="https://github.com/versatiles-org/versatiles-documentation/assets/1007187/49698707-69a2-423d-b92c-6c9b902a6162">

/cc @yetzt
